mat_file_path: 'C:\BBP\ecodeanalysis\data\01_raw\matData_2022-05-30'
test_file_name: 'aCell202_1.mat'
test_save: 'C:\BBP\ecodeanalysis\data\02_intermediate\test.csv'

repetitions_column: 'repetition'
protocol_name: 'protocol_name'
refresh_df: True

columns:
  group_col_name_type: 'cell_group_type'
  group_col_name_in_pc: 'cell_group_in_pc'
  cell_type_column: 'cellType'

analysis:
  savepath: 'C:\BBP\ecodeanalysis\data\031_raw_data_analysis\html_files'
  savefile_type: "celltype_sep"
  savefile_in_pc: "in_pc_sep"
  stim_groups_dict:
    apwaveform: [60, 100, 140, 180, 220]
    idrest: [100, 125, 150, 175, 200, 225, 250, 275, 300]

statistical_analysis_dict:
  savepath: 'C:\BBP\ecodeanalysis\data\04_statistical_analysis'
  class_features: 'cellType'
  run_t_test: True
  run_mann_whitney: True

  non_feat_cols: ['cellType', 'test_type']
  p_min: 0.05
  p_max: 0.8
  filler_value: 0.5


  boxplot_dict:
    boxplot_savefile: 'boxplots'
    features_markers: ['apw', 'idrest']

  t_test_dict:
    features_markers: ['mean', 'stdev', 'first', 'second', 'frequency', 'vHold' ]
    report_save_path: 'C:\BBP\ecodeanalysis\data\04_statistical_analysis'
    graph_folder: 't_test_heatmaps'
    t_test_report_name: 't_test_report'
    aggregartion_level: 'cellType'
    cells_to_drop: ['SNcDA', 'DA','SNcDAProj','DAFill', 'DA60','DAP0', 'DAP2','DAP3',
              'DAP4','DAFillP4','DAP5', 'DAFillP5', 'DAP28','DAFillP28', 'DAP56', 'NO']

    cellType_col: 'cellType'

  mann_whitney_dict:
    features_markers: [ 'mean', 'stdev', 'first', 'second', 'frequency', 'vHold' ]
    report_save_path: 'C:\BBP\ecodeanalysis\data\04_statistical_analysis'
    graph_folder: 'mann_whitney_heatmaps'
    t_test_report_name: 'mann_whitney_report'
    aggregartion_level: 'cellType'
    cells_to_drop: ['SNcDA', 'DA','SNcDAProj','DAFill', 'DA60','DAP0', 'DAP2','DAP3',
              'DAP4','DAFillP4','DAP5', 'DAFillP5', 'DAP28','DAFillP28', 'DAP56', 'NO']
    cellType_col: 'cellType'


reports:
  report_02_intermediate:
    file_writing_path: 'C:\BBP\ecodeanalysis\data\08_reporting\report_02_intermediate\pdf_files'
    report_writing_path: 'C:\BBP\ecodeanalysis\data\08_reporting\report_02_intermediate\report_02_intermediate.pdf'
    treshold_mult: 8

  report_03_primary:
    file_writing_path: 'C:\BBP\ecodeanalysis\data\08_reporting\report_03_primary\pdf_files'
    report_writing_path: 'C:\BBP\ecodeanalysis\data\08_reporting\report_03_primary\report_03_primary.pdf'
    treshold_mult: 6

reformatting_params:
  treshold_tau: 60
  features_w_no_peaks: [

      'apwaveform_AP_mean_stim_60',
      'apwaveform_AP_stdev_stim_60',
      'apwaveform_first_AP_voltage_stim_60',
      'apwaveform_first_ISI_stim_60',

      'apwaveform_second_AP_voltage_stim_60',
      'apwaveform_second_ISI_stim_60',

      'apwaveform_AP_mean_stim_100',
      'apwaveform_AP_stdev_stim_100',
      'apwaveform_first_AP_voltage_stim_100',
      'apwaveform_first_ISI_stim_100',
      'apwaveform_second_AP_voltage_stim_100',
      'apwaveform_second_ISI_stim_100',

      'idrest_AP_mean_stim_50',
      'idrest_AP_stdev_stim_50',
      'idrest_first_AP_voltage_stim_50',
      'idrest_first_ISI_stim_50',
      'idrest_second_AP_voltage_stim_50',
      'idrest_second_ISI_stim_50',
      'idrest_AP_mean_stim_75',
      'idrest_AP_stdev_stim_75',
      'idrest_first_AP_voltage_stim_75',
      'idrest_first_ISI_stim_75',
      'idrest_second_AP_voltage_stim_75',
      'idrest_second_ISI_stim_75',
      'idrest_AP_mean_stim_100',
      'idrest_AP_stdev_stim_100',
      'idrest_first_AP_voltage_stim_100',
      'idrest_first_ISI_stim_100',
      'idrest_second_AP_voltage_stim_100',
      'idrest_second_ISI_stim_100',
  ]
  group_mapping_params:
    group_mapping_dict_type: {
              'L5FS': 'L5FS',
           'SNcDA': 'DA_type',
           'L2IN': 'L2IN',
           'L5PC': 'L5PC',
           'NO': 'Others',
           'L2PC': 'L2PC',
           'L5IN': 'L5IN',
           'Amygdala': 'Amygdala',
           'DA': 'DA_type',
           'CA1PC': 'CA1',
           'SNcDAProj': 'DA_type',
           'DAFill': 'DA_type',
           'DA60': 'DA_type',
           'DAP0': 'DA_type',
           'DAP2': 'DA_type',
           'DAP3': 'DA_type',
           'DAP4': 'DA_type',
           'DAFillP4': 'DA_type',
           'DAP5': 'DA_type',
           'DAFillP5': 'DA_type',
           'DAP28': 'DA_type',
           'DAFillP28': 'DA_type',
           'DAP56': 'DA_type'}
    group_mapping_dict_in_pc: {
      'L5FS': 'FS',
      'SNcDA': 'DA_type',
      'L2IN': 'IN',
      'L5PC': 'PC',
      'NO': 'Others',
      'L2PC': 'PC',
      'L5IN': 'IN',
      'Amygdala': 'Amygdala',
      'DA': 'DA_type',
      'CA1PC': 'PC',
      'SNcDAProj': 'DA_type',
      'DAFill': 'DA_type',
      'DA60': 'DA_type',
      'DAP0': 'DA_type',
      'DAP2': 'DA_type',
      'DAP3': 'DA_type',
      'DAP4': 'DA_type',
      'DAFillP4': 'DA_type',
      'DAP5': 'DA_type',
      'DAFillP5': 'DA_type',
      'DAP28': 'DA_type',
      'DAFillP28': 'DA_type',
      'DAP56': 'DA_type' }

cellinfo:
  category: 'aCell'
  sub_category: 'cellInfo'
  protocol: 'protocol'
  cell_type_column: 'cellType'
  cell_id_column: 'id'
  specie_name: 'species'
  specie_col: 'species'

cells_list:
  status_column: ' Status'
  id_column: 'CellID'

apwaveform_dict:
  protocol_tag: 'APWaveform'
  protocol_id: 'protocol_name'
  repetitions_column: 'repetition'
  stim_treshold: 100
  stim_col: 'stim'
  spike_col: 'spikecount'


  pivot_dict:
    index_columns: ['stim', 'protocol_name', 'stim_start', 'stim_end']
    pivot_index: ['protocol_name', 'stim_start', 'stim_end']
    pivot_columns: 'stim'

  trace_level:
    stimulation_column: 'stim'
    stimulations_to_keep: [60, 100, 140, 180, 220]
    trace_level_columns: [ 'ids',
                              'stim',
                              'stim_actual',
                              'vHold',
                              'spikecount',
                              'peak_time',
                              'peak_voltage',
                              'ISI_values',
                              'min_AHP_indices',
                              'min_AHP_time',
                              'min_AHP_voltage',
                              'AP_begin_voltage',
                              'AP_begin_time',
                              'AP_amplitude',
                              'AP_half_width',
                              'AP_width',
                              'AP_rise_time',
                              'AP_fall_time',
                              'time_to_AP_peak',
                              'AHP_duration',
                              'AHP_fall_tau',
                              #'AHP_fall_A',
                              #'AHP_rise_m',
                              #'AHP_rise_c',
                            ]
  preprocessing_columns: [
                          'vHold',
                          'stim_start',
                          'stim_end',
                          'spikecount',
                          'AP_begin_voltage',
                          'peak_time',
                          'peak_voltage',
                          'AHP_fall_tau',
                          'ISI_values',
                          'stim', 'protocol_name'
                          ]

  double_extract_features: ['vHold', 'stim_start', 'stim_end', 'spikecount']
  single_extract_features: ['AP_begin_voltage','peak_time','peak_voltage','AHP_fall_tau','ISI_values']

  freq_dict:
    stim_lenght: 'stim_lenght'
    stim_start: 'stim_start'
    stim_end: 'stim_end'
    peak_frequency : 'peak_frequency'
    spikecount : 'spikecount'
  ap_potential:
    AP_begin_voltage: 'AP_begin_voltage'
    min_list_size: 2
    AP_mean: 'AP_mean'
    AP_stdev: 'AP_stdev'
    AP_mean_wo_first: 'AP_mean_wo_first'
    AP_stdev_wo_first: 'AP_stdev_wo_first'

    first_AP_voltage: 'first_AP_voltage'
    second_AP_voltage: 'second_AP_voltage'
  ISI_values:
    ISI_values: "ISI_values"
    first_ISI: "first_ISI"
    second_ISI: "second_ISI"
    min_list_size: 2
  ahp_values:
    tau_mean: 'tau_mean'
    tau_stdev: 'tau_stdev'
    ahp_fall_tau: 'AHP_fall_tau'
    first_fall_tau: 'first_fall_tau'
    second_fall_tau: 'second_fall_tau'
  out_features_base: ['vHold', 'spikecount']


idrest_dict:
  protocol_tag: 'IDRest'
  protocol_id: 'protocol_name'
  repetitions_column: 'repetition'
  stim_treshold: 100
  stim_col: 'stim'
  spike_col: 'spikecount'


  freq_dict:
    stim_lenght: 'stim_lenght'
    stim_start: 'stim_start'
    stim_end: 'stim_end'
    peak_frequency: 'peak_frequency'
    spikecount: 'spikecount'

  ap_potential:
    AP_begin_voltage: 'AP_begin_voltage'
    min_list_size: 2
    AP_mean: 'AP_mean'
    AP_stdev: 'AP_stdev'
    AP_mean_wo_first: 'AP_mean_wo_first'
    AP_stdev_wo_first: 'AP_stdev_wo_first'

    first_AP_voltage: 'first_AP_voltage'
    second_AP_voltage: 'second_AP_voltage'

  ISI_values:
    ISI_values: "ISI_values"
    first_ISI: "first_ISI"
    second_ISI: "second_ISI"
    min_list_size: 2

  out_features_base: [ 'vHold', 'spikecount', 'ISI1_time_vs_I_m', 'ISI1_time_vs_I_c',
    'AP1_time_vs_I_m', 'AP1_time_vs_I_c']

  preprocessing_columns: [
    'vHold',
    'stim_start',
    'stim_end',
    'spikecount',
    'AP_begin_voltage',
    'peak_time',
    'peak_voltage',
    'ISI_values',
    'stim', 'protocol_name', 'ISI1_time_vs_I_m', 'ISI1_time_vs_I_c',
    'AP1_time_vs_I_m', 'AP1_time_vs_I_c'
  ]

  trace_level:
    stimulation_column: 'stim'
    stimulations_to_keep: [ 50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300]
    trace_level_columns: [    'ids',
                  'stim',
                  'stim_actual',
                  'vHold',
                  'spikecount',
                  'peak_time',
                  'peak_voltage',
                  'ISI_values',
                  'min_AHP_indices',
                  'min_AHP_time',
                  'min_AHP_voltage',
                  'AP_begin_voltage',
                  'AP_begin_time',
                  'AP_amplitude',
                  'initial_accommodation',
                  'steady_state_accommodation',
                  'intermediate_accommodation',
                  'last_accommodation',
                  'ISI_CV',
                  'adaptation_index',
    ]
  double_extract_features: [ 'vHold', 'stim_start', 'stim_end', 'spikecount' ]
  single_extract_features: [ 'AP_begin_voltage','peak_time','peak_voltage','ISI_values' ]
  pivot_dict:
    index_columns: ['stim', 'protocol_name', 'stim_start', 'stim_end']
    pivot_index: ['protocol_name', 'stim_start', 'stim_end']
    pivot_columns: 'stim'

clustering_dict:
  data_prep:
    clustering_markers: ['AP_mean', 'first_AP_voltage', 'first_ISI', 'first_fall_tau',
           'peak_frequency', 'tau_mean']
    protocol_markers: ['apw', 'idrest']
  clustering_param:
    clustering_method: 'agglomerative' #kmean, k_minibatch_mean
    agg_method: 'ward'
    n_clusters_list: [4,5,6,7,8,9,10, 11]
    fig_savepath: 'data/05_clustering/figures'
